language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $WEBHOST_DOMAIN\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key $WEBHOST_USER@$WEBHOST_DOMAIN pwd
script:
- npm test
- npm run build
deploy:
- provider: script
- script: bash ./deploy.sh